---
- name: Adding Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Saving Debian release version into a variable
  shell: "lsb_release -cs"
  register: os_version

- name: Adding Docker apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ os_version.stdout }} stable"
    state: present

- name: Installing Docker
  apt:
    state: present
    update_cache: yes
    force_apt_get: yes
    name:
      - docker-ce={{ docker_ce_version }}
      - docker-ce-cli={{ docker_ce_cli_version }}
      - containerd.io={{ containerd_version }}

# 'state: present' -> if group exist = pass; otherwise create it.
- name: Creating Docker Group
  group:
    name: docker
    state: present

- name: Adding user '{{ default_user }}' to docker group
  user:
    name: "{{ default_user }}"
    groups: "docker"
    append: yes

- name: Copying custom daemon.json file
  ansible.builtin.copy:
    src: ../files/daemon.json
    dest: /etc/docker
    owner: root
    group: root
    mode: "0644"
    force: yes

- name: Ensuring docker service is running
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v{{ compose_version }}/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
