---
- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Save Debian release version into a variable
  shell: "lsb_release -cs"
  register: os_version

- name: Add Docker apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ os_version.stdout }} stable"
    state: present

- name: Install Docker
  apt: 
    state: present 
    update_cache: yes 
    force_apt_get: yes
    name: 
      - docker-ce={{ docker_ce_version }}
      - docker-ce-cli={{ docker_ce_cli_version }}
      - containerd.io={{ containerd_version }}

# 'state: present' -> if group exist = pass; otherwise create it. 
- name: Create Docker Group
  group:
    name: docker
    state: present

- name: Add user '{{ default_user }}' to docker group
  user:
    name: "{{ default_user }}"
    groups: "docker"
    append: yes

- name: Ensure docker service is running
  systemd: 
    name: docker 
    state: started 
    enabled: yes   

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v{{ compose_version }}/docker-compose-linux-aarch64
    dest: /usr/local/bin/docker-compose
    checksum: sha256:14d31297794868520cb2e61b543bb1c821aaa484af22b397904314ae8227f6a2
    mode: 0755
