# test if claim is successful:
# curl http://localhost:32400/identity
version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:${TAG}
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=America/LOS_ANGELES
      - PLEX_CLAIM=${CLAIMTOKEN}
      - ADVERTISE_IP=http://${HOSTIP}:32400/
    hostname: plex.shakir.cloud
    volumes:
      - /plex/database:/config
      - /plex/transcode:/transcode
      - /plex/data:/data
    mem_limit: 8000m
