---
# vars file for commons
packages: [ 'zip', 'rsync', 'python3-pip' , 'python3-virtualenv', 'ca-certificates', 
            'apt-transport-https', 'gnupg', 'lsb-release', 'htop', 
            'curl', 'vim', 'figlet', 'git' ]
