version: "3"
services:
  app:
    image: mattermost/focalboard
    container_name: focalboard
    volumes:
      - /galaxy/data/focalboard:/opt/focalboard/data
    ports:
      - 7180:8000
    environment:
      - VIRTUAL_HOST=focalboard.local
      - VIRTUAL_PORT=8000
