version: "2.1"
services:
  calibre-web:
    image: ghcr.io/linuxserver/calibre-web:${TAG}
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/calibre-web:calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    volumes:
      - /galaxy/data/calibre-web:/config
      - /galaxy/data/calibre:/books
    ports:
      - 4463:8083
    restart: unless-stopped
