version: '3.6'

services:
  flame:
    image: pawelmalak/flame:${TAG}
    container_name: flame
    volumes:
      - /galaxy/data/flame:/app/data
    ports:
      - 5005:5005
    environment:
      - PASSWORD=${PASSWORD}
    restart: unless-stopped
