version: '3.6'

volumes:
  flame:

services:
  flame:
    image: pawelmalak/flame
    container_name: flame
    volumes:
      - /data/flame:/app/data
    ports:
      - 5005:5005
    environment:
      - PASSWORD=shakir
    restart: unless-stopped
