version: '3'

services:
  planka:
    image: meltyshev/planka:latest
    command: >
      bash -c
        "for i in `seq 1 30`; do
          ./start.sh &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 seconds...\";
          sleep 5;
        done; (exit $$s)"
    restart: unless-stopped
    volumes:
      - /data/planka/user-avatars:/app/public/user-avatars
      - /data/planka/background-images:/app/public/project-background-images
      - /data/planka/attachments:/app/public/attachments
    ports:
      - 5595:1337
    environment:
      # If you encounter login errors, open web-browser's console
      # if it's websocket erros then enable websockets in Nginx reverse proxy.
      - BASE_URL=https://planka.shakir.cloud
      - DATABASE_URL=postgresql://postgres@postgres/planka
      - SECRET_KEY=4c12e512c74a18d54fdb70f1
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - /data/planka:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  user-avatars:
  project-background-images:
  attachments:
  db-data:
