---
version: "2.1"
services:
  changedetection:
    image: lscr.io/linuxserver/changedetection.io:latest
    container_name: changedetection
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - BASE_URL=https://change.shakir.cloud
    volumes:
      - /data/changedetection:/config
    ports:
      - 5900:5000
    restart: unless-stopped
