---
# tasks file for gitlab
# https://gitlab-runner-downloads.s3.amazonaws.com/latest/index.html
- name: Downloading Gitlab Runner
  get_url:
    url: "{{ gitlab_deb_pkg_url }}"
    dest: /tmp/
    mode: 0755

- name: Installing Gitlab Runner
  apt:
    deb: /tmp/{{ gitlab_deb_pkg_name }}

- name: Deleting Gitlab Runner dep package
  file:
    path: /tmp/{{ gitlab_deb_pkg_name }}
    state: absent

- name: Adding user 'gitlab-runner' to docker group
  user:
    name: gitlab-runner
    groups: docker
    append: yes

- name: Ensuring gitlab-runner is running
  systemd:
    name: gitlab-runner
    state: started
    enabled: yes
