---
# -----------------
# IMPORTANT:
# See these Gitlab deprications:
# - registration-tokens & gitlab-runner register command:
#     https://gitlab.com/gitlab-org/gitlab/-/issues/380872
# -----------------

- name: Registering Gitlab Runner (system-mode)
  when: registration_token | default('', true) | trim != ''
  register: create
  loop: "{{ list_of_runners }}"
  # --tag-list -> comma separated tags
  shell: |
    gitlab-runner register \
    --description "provisioned by Ansible in {{ runner_description }} @ {{ inventory_hostname }}" \
    --non-interactive \
    --run-untagged="false" \
    --locked="false" \
    --access-level="not_protected" \
    --url "https://gitlab.com" \
    --registration-token "{{ registration_token }}" \
    --executor shell \
    --tag-list="{{ inventory_hostname }}" \

# Print this message if the gitlab-ci registration token was not exported as env var
- name: print msg
  when: create.changed == false
  debug:
    msg:
      - => Registration token variable 'CI_TOKEN' is not set. No runner was registered.
      - => export CI_TOKEN=<yourToken> before running this role.
