---
version: "2"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:${TAG}
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://{HOSTIP}:6875
      - DB_HOST=bookstack_db
      - DB_PORT=3306
      - DB_USER=${BOOKSTACK_DBUSER}
      - DB_PASS=${BOOKSTACK_DBPWD}
      - DB_DATABASE=bookstackapp
    volumes:
      - /galaxy/data/bookstack/app:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${BOOKSTACK_MYSQLROOTPWD}
      - TZ=${TIMEZONE}
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=${BOOKSTACKMYSQLUSER}
      - MYSQL_PASSWORD=${BOOKSTACK_MYSQLPWD}
    volumes:
      - /galaxy/data/bookstack/db:/config
    restart: unless-stopped
