---
# docker playbook
- hosts: has_docker
  become: yes
  vars_files:
    - group_vars/all.yml
    - roles/docker/vars/main.yml

  tasks:
    - ansible.builtin.include_tasks:
        file: roles/docker/tasks/main.yml

    # - name: Rebooting...
    #   shell: "sleep 5 && reboot"
    #   async: 1
    #   poll: 0
