---
# gitlab playbook
- hosts: has_gitlab
  become: yes
  vars_files:
    - group_vars/all.yml
    - roles/gitlab/vars/main.yml

  tasks:
    - ansible.builtin.include_tasks:
        file: roles/gitlab/tasks/main.yml
    - ansible.builtin.include_tasks:
        file: roles/gitlab/tasks/register_runner.yml

    # - name: Rebooting...
    #   shell: "sleep 5 && reboot"
    #   async: 1
    #   poll: 0
