---
- hosts: server1
  become: yes
  vars:
    # Update this path based playbook/server (shared folder path on the NFS server)
    - nfs_shared_dir_path: "/volume1/test"
  vars_files:
    - group_vars/all.yml
    - roles/commons/vars/main.yml
    - roles/docker/vars/main.yml
    - roles/gitlab/vars/main.yml
    - roles/nfs/vars/main.yml

  tasks:
    # Order of tasks execution matters
    - ansible.builtin.include_tasks:
        file: roles/commons/tasks/main.yml
    - ansible.builtin.include_tasks:
        file: roles/docker/tasks/main.yml
    - ansible.builtin.include_tasks:
        file: roles/gitlab/tasks/main.yml
    - ansible.builtin.include_tasks:
        file: roles/gitlab/tasks/register_runner.yml
    - ansible.builtin.include_tasks:
          file: roles/nfs/tasks/main.yml

    # - name: Rebooting...
    #   shell: "sleep 5 && reboot"
    #   async: 1
    #   poll: 0
