---
# Supervised gitlab runner registration
- hosts: "{{ host }}"
  become: yes

  # Manually enter hostname in the CLI
  vars_prompt:
    - name: host
      prompt: "Enter hostname..."
      private: false

  vars_files:
    - ../group_vars/all.yml
    - ../roles/gitlab/vars/main.yml

  tasks:
    - ansible.builtin.include_tasks:
        file: ../roles/gitlab/tasks/register_runner.yml
