---
stages:
  - deploy

homeapps-deployment:
  tags:
    - galaxy

  stage: deploy

  script:
    - docker-compose -f apps/calibre/docker-compose.yml up -d
    - docker-compose -f apps/calibre-web/docker-compose.yml up -d
    - docker-compose -f apps/change-detection/docker-compose.yml up -d
    - docker-compose -f apps/flame/docker-compose.yml up -d
    - docker-compose -f apps/memos/docker-compose.yml up -d
    - docker-compose -f apps/planka/docker-compose.yml up -d
    - docker-compose -f apps/uptime-kuma/docker-compose.yml up -d
    - docker-compose -f apps/wikijs/docker-compose.yml up -d

  when: manual

media-server-deployment:
  tags:
    - mediaserver

  stage: deploy

  script:
    # test if claim is successful:
    # curl http://localhost:32400/identity
    - pwd
    - docker-compose -f apps/plex/docker-compose.yml up -d

  when: manual
