---
stages:
  - deploy

homeapps:
  tags:
    - galaxy

  stage: deploy

  script:
    - docker-compose -f apps/calibre/docker-compose.yml up -d
    - docker-compose -f apps/calibre-web/docker-compose.yml up -d
    - docker-compose -f apps/change-detection/docker-compose.yml up -d
    - docker-compose -f apps/flame/docker-compose.yml up -d
    - docker-compose -f apps/memos/docker-compose.yml up -d
    - docker-compose -f apps/planka/docker-compose.yml up -d
    - docker-compose -f apps/uptime-kuma/docker-compose.yml up -d
    - docker-compose -f apps/wikijs/docker-compose.yml up -d
    - docker run -d -p 4567:4567 -v /galaxy/data/gollum/wiki:/wiki gollumwiki/gollum:v5.3.0

  when: manual

mediaserver:
  tags:
    - mediaserver

  stage: deploy

  script:
    # test if claim is successful:
    # curl http://localhost:32400/identity
    - pwd
    - docker-compose -f apps/plex/docker-compose.yml up -d

  when: manual
