---
stages:
  - deploy

homeapps:
  tags:
    - galaxy

  stage: deploy

  before_script:
    - docker kill -s=9 $(docker ps -aq) || true

  script:
    - docker-compose -f apps/calibre/docker-compose.yml up --force-recreate -d
    - docker-compose -f apps/calibre-web/docker-compose.yml up --force-recreate -d
    - docker-compose -f apps/change-detection/docker-compose.yml up --force-recreate -d
    - docker-compose -f apps/flame/docker-compose.yml up --force-recreate -d
    - docker-compose -f apps/memos/docker-compose.yml up --force-recreate -d
    - docker-compose -f apps/uptime-kuma/docker-compose.yml up --force-recreate -d
    - docker-compose -f apps/bookstack/docker-compose.yml up --force-recreate -d
    - docker-compose -f apps/focalboard/docker-compose.yml up --force-recreate -d
    - |
      docker rm -f gollum &&
      docker run -d -p 4567:4567 --name gollum -v /galaxy/data/gollum/wiki:/wiki gollumwiki/gollum:v5.3.0

  when: manual

mediaserver:
  tags:
    - mediaserver

  stage: deploy

  script:
    # To test if the claim was successful:
    # curl http://localhost:32400/identity
    - pwd
    - docker-compose -f apps/plex/docker-compose.yml up -d

  when: manual
